version: "3.8"

name: transcription-ui

services:
  mariadb:
    image: mariadb:11.0.2
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=${MARIADB_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    environment: &api_environment
      DATABASE_URL: mysql+pymysql://${MARIADB_USER}:${MARIADB_PASSWORD}@mariadb:3306/${MARIADB_DATABASE}
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379/0
      MJML_RENDER_URL: http://mjml:3000/render
      FILES_MAX_SIZE_BYTE: ${FILES_MAX_SIZE_BYTE}
      FILES_STORAGE_PATH: /files
      MODELS_STORAGE_PATH: /models
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_TOKEN_EXPIRY_HOURS: ${JWT_TOKEN_EXPIRY_HOURS}
      CONTACT_EMAIL: ${CONTACT_EMAIL}
      PASSWORD_RESET_EXPIRY_MINUTES: ${PASSWORD_RESET_EXPIRY_MINUTES}
      CELERY_CONCURRENCY: ${CELERY_CONCURRENCY}
    volumes:
      - ./data/models:/models
      - ./data/files:/files
    depends_on:
      - mariadb
      - redis
      - worker
      - mjml
    restart: always

  worker:
    environment:
      <<: *api_environment
    volumes:
      - ./data/models:/models
      - ./data/files:/files
    depends_on:
      - mariadb
      - redis
      - mjml
    restart: always

  caddy:
    build:
      context: ./caddy
    environment:
      FILES_MAX_SIZE_BYTE: ${FILES_MAX_SIZE_BYTE}
    command:
      - /bin/sh
      - -c
      - |
        envsubst '$$CADDY_DOMAIN_NAME $$FILES_MAX_SIZE_BYTE' < /etc/caddy/Caddyfile.template > /etc/caddy/Caddyfile &&
        caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
    depends_on:
      - app
      - api
    restart: always

  mjml:
    build:
      context: ../api/mjml
    restart: always