version: "3.8"

services:
  caddy:
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile.prod:/etc/caddy/Caddyfile.template:ro
      - app-build:/app/build:ro
    environment:
      CADDY_DOMAIN_NAME: ${CADDY_DOMAIN_NAME}

  api:
    environment: &api_environment
      BASE_URL: ${BASE_URL}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    command:
      [
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--proxy-headers",
        "--forwarded-allow-ips",
        "*",
      ]

  worker:
    environment: *api_environment
    command:
      [
        "celery",
        "-A",
        "worker.app",
        "worker",
        "--loglevel=info",
        "--pool=prefork",
        "--concurrency=${CELERY_CONCURRENCY}",
      ]

  app:
    build:
      context: ../app
      target: builder
    volumes:
      - app-build:/app/build

  mjml:
    command: ["yarn", "prod"]

volumes:
  app-build:
